export const indicatorWrapper: string
export const indicator: string
export const indicatorActive: string
export const indRow: string
export const indCol: string
export const bottomLeft: string
export const bottomRight: string
export const small: string
export const medium: string
export const large: string